# Generated by Django 2.0.2 on 2018-03-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180302_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('A', 'active'), ('F', 'finished'), ('R', 'resolved')], default='A', max_length=1),
        ),
    ]
