# Generated by Django 2.0.2 on 2018-03-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='participant',
            new_name='event_participant',
        ),
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.DecimalField(decimal_places=8, help_text='How much do you bet', max_digits=20),
        ),
    ]
