# Generated by Django 2.0.2 on 2018-03-07 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_auto_20180306_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.DecimalField(decimal_places=8, help_text='(How much do you bet)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='bet',
            name='event_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='events.EventsParticipant'),
        ),
    ]
