# Generated by Django 2.0.2 on 2018-03-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_auto_20180307_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.DecimalField(decimal_places=8, help_text='(How much do you bet)', max_digits=15),
        ),
    ]
